In [1]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

In [31]:
# NOTE:
# If you encounter any issues importing the customer_churn.db file,
# run the code below to create the database locally from the provided Excel file OR, can directly import data & start working.

# Otherwise, skip this step and proceed to the next section: Data Import

# Excel file path
excel_file = 'customer_churn_data_raw.xlsx'

# Create SQLite database connection
conn = sqlite3.connect('customer_churn.db')

# Read all sheet names from Excel file
excel_data = pd.ExcelFile(excel_file)

# Loop through each sheet and store as separate table
for sheet in excel_data.sheet_names:
    df = pd.read_excel(excel_file, sheet_name=sheet) # Read sheet into dataframe
    # Write dataframe to SQLite table
    df.to_sql(
        name=sheet,          # Table name = Sheet name
        con=conn,
        if_exists='replace', # Replace table if already exists
        index=False
    )

# Close connection
conn.close()

print("All sheets successfully converted into SQLite tables.")

All sheets successfully converted into SQLite tables.

In [32]:
##1. Import database / data

In [33]:
# Data Import: db file to pandas, storing each table to a separate df

# Connect to SQLite database
conn = sqlite3.connect('customer_churn.db')

# sql query to Get all table names
sql_query = """
        SELECT name
        FROM sqlite_master
        WHERE type='table';
"""

# read sql query in pandas
tables = pd.read_sql(sql_query, conn)

# create dataframe for each table
for table_name in tables['name']:
    df = pd.read_sql(f"SELECT * FROM {table_name}", conn) # Read table into dataframe
    globals()[f"df_{table_name}"] = df                    # Create dynamic dataframe name
    print(f"Created dataframe: df_{table_name}")

# Close connection
conn.close()

Created dataframe: df_db_customer
Created dataframe: df_db_subscription
Created dataframe: df_db_support

In [34]:
# Print table names and column names
conn = sqlite3.connect('customer_churn.db')

for table_name in tables['name']:
    print(f"\nTable Name: {table_name}")
    # Get column information
    columns_query = f"PRAGMA table_info({table_name});"
    columns = pd.read_sql(columns_query, conn)
    print("Columns:")
    print(columns['name'].tolist())

# Close connection
conn.close()

Table Name: db_customer
Columns:
['customerid', 'name', 'country', 'state', 'gender', 'dob', 'interests', 'pincode']

Table Name: db_subscription
Columns:
['customerid', 'subscription_start_date', 'subscription_type', 'renewal_date', 'plan_type', 'contract_type', 'cancellation_date', 'cancellation_reason', 'monthly_charges', 'cltv', 'churn_score']

Table Name: db_support
Columns:
['customerid', 'complaint_date', 'escalations', 'csat_score', 'col_1', 'comment']

In [35]:
# df_db_customer.head() # customer table
df_db_customer.tail()

,customerid,name,country,state,gender,dob,interests,pincode
16,0020-JDNXP,rikim,India,Meghalaya,Female,1994-08-19 00:00:00,None,None
17,0021-IKXGC,vishakha,India,Rajasthan,Female,2000-09-02 00:00:00,None,None
18,0022-TCJCI,raghvendra,India,Telangana,Male,1983-12-30 00:00:00,None,None
19,0023-HGHWL,rishabh,India,Uttar Pradesh,Men,1991-05-14 00:00:00,None,None
20,0023-UYUPN,sudevi,India,Maharashtra,Women,1977-10-06 00:00:00,None,None

In [36]:
df_db_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerid  21 non-null     object
 1   name        21 non-null     object
 2   country     18 non-null     object
 3   state       21 non-null     object
 4   gender      21 non-null     object
 5   dob         21 non-null     object
 6   interests   4 non-null      object
 7   pincode     0 non-null      object
dtypes: object(8)
memory usage: 1.4+ KB

In [37]:
# a. rename col - name to customer_name
# b. drop columns - interest and pincode
# c. change data type - dob
# d. data standardization - gender
# e. fix missing values (using existing data) - country

In [38]:
# a. rename col - name to customer_name
df_db_customer.rename(columns = {'name' : 'customer_name'}, inplace= True)
print(df_db_customer.columns)

Index(['customerid', 'customer_name', 'country', 'state', 'gender', 'dob',
       'interests', 'pincode'],
      dtype='object')

In [39]:
# b. drop columns - interest and pincode

# df_db_customer.drop(df_db_customer.columns[-2:], axis=1)
# df_db_customer.drop(df_db_customer.columns[6:], axis=1)

df_db_customer.drop(columns=['interests', 'pincode'],inplace=True)  # using col name
print(df_db_customer.columns)

Index(['customerid', 'customer_name', 'country', 'state', 'gender', 'dob'], dtype='object')

In [40]:
# c. change data type - dob

df_db_customer['dob'] = pd.to_datetime(df_db_customer['dob'])

In [41]:
# d. data standardization - gender

# df_db_customer['gender'].unique()
df_db_customer['gender'] = df_db_customer['gender'].replace({'Men' : 'Male', 'Women' : 'Female'})
print(df_db_customer.info)

<bound method DataFrame.info of     customerid customer_name country          state  gender        dob
0   0002-ORFBO        keshav   India    Maharashtra    Male 1982-04-12
1   0003-MKNFE        raghav   India      Karnataka    Male 1995-11-23
2   0004-TLHLJ        lalita   India          Delhi  Female 1978-02-15
3   0011-IGKFF         mohan   India       Nagaland    Male 2001-08-30
4   0013-EXCHZ          mira   India          Delhi  Female 1990-05-05
5   0013-MHZWF         durga    None          Delhi  Female 1988-12-10
6   0013-SMEOE          mina   India      Meghalaya  Female 1976-09-21
7   0014-BMAQU         madan   India      Rajasthan    Male 1999-03-14
8   0015-UOCOJ          maya    None      Kathmandu  Female 1985-07-07
9   0016-QLJIS         arjun   Nepal      Kathmandu    Male 1993-10-29
10  0017-DINOC         shiva   India    Maharashtra    Male 1997-01-22
11  0017-IUDMW     rangadevi   India      Karnataka  Female 1981-06-18
12  0018-NYROU        chitra    None      Telangana  Female 2004-12-01
13  0019-EFAEP          raju   India      Meghalaya  Female 1992-04-25
14  0019-GFNTW        Madhav   India  Uttar Pradesh    Male 1979-11-11
15  0020-INWCK       parvati   India          Delhi  Female 1986-02-28
16  0020-JDNXP         rikim   India      Meghalaya  Female 1994-08-19
17  0021-IKXGC      vishakha   India      Rajasthan  Female 2000-09-02
18  0022-TCJCI    raghvendra   India      Telangana    Male 1983-12-30
19  0023-HGHWL       rishabh   India  Uttar Pradesh    Male 1991-05-14
20  0023-UYUPN        sudevi   India    Maharashtra  Female 1977-10-06>

In [42]:
# e. fix missing values (using existing data) - country
df_db_customer[df_db_customer['country'].isna()]

    customerid customer_name country      state  gender        dob
5   0013-MHZWF         durga    None      Delhi  Female 1988-12-10
8   0015-UOCOJ          maya    None  Kathmandu  Female 1985-07-07
12  0018-NYROU        chitra    None  Telangana  Female 2004-12-01

In [43]:
# country and state - unique value pair

# Creating state → country map from non-null rows
state_country_mapping = df_db_customer.dropna(subset=['country']).set_index('state')['country'].to_dict()

# Fill the missing country using State
df_db_customer['country'] = df_db_customer['country'].fillna(df_db_customer['state'].map(state_country_mapping))

In [44]:
print(df_db_customer.info)

<bound method DataFrame.info of     customerid customer_name country          state  gender        dob
0   0002-ORFBO        keshav   India    Maharashtra    Male 1982-04-12
1   0003-MKNFE        raghav   India      Karnataka    Male 1995-11-23
2   0004-TLHLJ        lalita   India          Delhi  Female 1978-02-15
3   0011-IGKFF         mohan   India       Nagaland    Male 2001-08-30
4   0013-EXCHZ          mira   India          Delhi  Female 1990-05-05
5   0013-MHZWF         durga   India          Delhi  Female 1988-12-10
6   0013-SMEOE          mina   India      Meghalaya  Female 1976-09-21
7   0014-BMAQU         madan   India      Rajasthan    Male 1999-03-14
8   0015-UOCOJ          maya   Nepal      Kathmandu  Female 1985-07-07
9   0016-QLJIS         arjun   Nepal      Kathmandu    Male 1993-10-29
10  0017-DINOC         shiva   India    Maharashtra    Male 1997-01-22
11  0017-IUDMW     rangadevi   India      Karnataka  Female 1981-06-18
12  0018-NYROU        chitra   India      Telangana  Female 2004-12-01
13  0019-EFAEP          raju   India      Meghalaya  Female 1992-04-25
14  0019-GFNTW        Madhav   India  Uttar Pradesh    Male 1979-11-11
15  0020-INWCK       parvati   India          Delhi  Female 1986-02-28
16  0020-JDNXP         rikim   India      Meghalaya  Female 1994-08-19
17  0021-IKXGC      vishakha   India      Rajasthan  Female 2000-09-02
18  0022-TCJCI    raghvendra   India      Telangana    Male 1983-12-30
19  0023-HGHWL       rishabh   India  Uttar Pradesh    Male 1991-05-14
20  0023-UYUPN        sudevi   India    Maharashtra  Female 1977-10-06>

In [45]:
df_db_customer[df_db_customer['country'].isna()] # no null value in country col

Empty DataFrame
Columns: [customerid, customer_name, country, state, gender, dob]
Index: []

In [46]:
df_db_subscription.head() # subcription table

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,None,None,13.99,627,12
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,None,None,6.99,210,34
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,None,None,22.99,1725,8
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88

In [47]:
df_db_subscription.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customerid               21 non-null     object
 1   subscription_start_date  21 non-null     object
 2   subscription_type        21 non-null     object
 3   renewal_date             21 non-null     object
 4   plan_type                21 non-null     object
 5   contract_type            21 non-null     object
 6   cancellation_date        6 non-null      object
 7   cancellation_reason      6 non-null      object
 8   monthly_charges          21 non-null     float64
 9   cltv                     21 non-null     int64
 10  churn_score              21 non-null     int64
dtypes: float64(1), int64(2), object(8)
memory usage: 1.9+ KB

In [48]:
# change data type to date - subscription_start_date , renewal_date, cancellation_date
date_col = ['subscription_start_date', 'renewal_date', 'cancellation_date']

df_db_subscription[date_col] = df_db_subscription[date_col].apply(pd.to_datetime)
df_db_subscription.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customerid               21 non-null     object
 1   subscription_start_date  21 non-null     datetime64[ns]
 2   subscription_type        21 non-null     object
 3   renewal_date             21 non-null     datetime64[ns]
 4   plan_type                21 non-null     object
 5   contract_type            21 non-null     object
 6   cancellation_date        6 non-null      datetime64[ns]
 7   cancellation_reason      6 non-null      object
 8   monthly_charges          21 non-null     float64
 9   cltv                     21 non-null     int64
 10  churn_score              21 non-null     int64
dtypes: datetime64[ns](3), float64(1), int64(2), object(5)
memory usage: 1.9+ KB

In [49]:
df_db_support.head() # support table

,customerid,complaint_date,escalations,csat_score,col_1,comment
0,0003-MKNFE,2024-08-28 00:00:00,N,60,None,service issue
1,0003-MKNFE,2024-08-28 00:00:00,Y,10,None,demaned refund
2,0013-EXCHZ,2024-01-20 00:00:00,Y,20,None,None
3,0013-MHZWF,2025-03-18 00:00:00,N,90,None,guidance to renew
4,0013-SMEOE,2024-11-01 00:00:00,N,30,None,None

In [50]:
df_db_support.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customerid      9 non-null      object
 1   complaint_date  9 non-null      object
 2   escalations     9 non-null      object
 3   csat_score      9 non-null      int64
 4   col_1           0 non-null      object
 5   comment         4 non-null      object
dtypes: int64(1), object(5)
memory usage: 564.0+ bytes

In [51]:
# drop columns
df_db_support.drop(columns=['col_1', 'comment'], inplace=True)

In [52]:
# change data type to date - complaint_date

df_db_support['complaint_date'] = pd.to_datetime(df_db_support['complaint_date'])
df_db_support.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customerid      9 non-null      object
 1   complaint_date  9 non-null      datetime64[ns]
 2   escalations     9 non-null      object
 3   csat_score      9 non-null      int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 420.0+ bytes

In [53]:
##_____3.Feature Engineering & Data Analysis
 
# create a new col using existing col - churn flag

# Customer is churned if cancellation_date is not null
df_db_subscription['churn_flag'] = np.where(df_db_subscription['cancellation_date'].notna(), 1, 0)
df_db_subscription.head()

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score,churn_flag
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaT,None,13.99,627,12,0
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91,1
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,NaT,None,6.99,210,34,0
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,NaT,None,22.99,1725,8,0
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88,1

In [54]:
#MERGE DATAFRAMES - JOINS
# Note: while merging df's always check the shape before and after

In [55]:
df = (df_db_subscription
            .merge(df_db_customer, on = 'customerid', how= 'left')
            .merge(df_db_support, on = 'customerid', how= 'left') )

In [60]:
df_db_subscription.shape

(21, 12)

In [58]:
df_db_subscription.head()

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score,churn_flag
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaT,None,13.99,627,12,0
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91,1
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,NaT,None,6.99,210,34,0
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,NaT,None,22.99,1725,8,0
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88,1

In [61]:
print('df_db_subscription unique value:', df_db_subscription['customerid'].nunique())
print('df_db_customer unique value:', df_db_customer['customerid'].nunique())
print('df_db_support unique value:', df_db_support['customerid'].nunique())
print('df_db_support all value:', df_db_support['customerid'].size)

df_db_subscription unique value: 21
df_db_customer unique value: 21
df_db_support unique value: 7
df_db_support all value: 9